# SITE
# 12-FEB-2023 
# Kirby 3.7 >=
title: Site

sections:
  sitemap:
    label: 📁 Site Map
    type: pages
    layout: list
    status: listed

  pages:
    label: 📁 Páginas
    type: pages
    layout: cardlets
    status: unlisted
